
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 60023
  password: shopify_app_demo
  user: postgres

development:
  <<: *default
  database: shopify_app_demo_development


test:
  <<: *default
  database: shopify_app_demo_test

#
production:
  <<: *default
  database: shopify_app_demo_production
  username: <%= ENV['SHOPIFY_APP_DEMO_DATABASE_USER'] %>
  password: <%= ENV['SHOPIFY_APP_DEMO_DATABASE_PASSWORD'] %>
